analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.06504637212492526
  brandStrength: 1
  lightness: 0.759003025945276
  brandColors:
    - '#0D080F'
    - '#FFFDFF'
    - '#FFAFA3'
    - '#FF2B04'
    - '#FF742B'
  rhythmicContrast: 0.7530727332923561
typography_spectrum: 0.1989247
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9731183
favicon: null
name: PANIC
